### ISSUE TITLE
'Filter reports caused by browser extensions' keeps disabling itself

### ISSUE THREAD

**Issue by revisiontroll** [report-uri/report-uri-bugs#154]
Whenever I switch the 'Filter reports caused by browser extensions' toggle to ON, if I click 'Save' it flips back to OFF. This is not the case for the three other toggles under 'Advanced Report Filters' (e.g. 'Filter Unactionable Reports'). I get the 'Filters Updated!' message, but the switch still reads as OFF. As far as I know the plan I'm on--750,000--should permit this function. I don't see anything in the FAQ or Documents indicating why this might be the case. Did I miss something?

Thank you.

Additional information: this occurs for both Firefox 89.0 and Chrome 91.0.4472.106 for Linux, in both normal and Private/Incognito windows.

**Comment by spaze** [comment]
Hi @revisiontroll, thanks for spotting and reporting this!

I've found the issue and it is indeed a problem and it's on our side - a space has been erroneously removed and it's now missing between two HTML attributes `checked[MISSINGSPACE]data` making it `checkeddata` instead of `checked data` so the toggle always appear disabled. However it's only a UI problem, the setting is saved and applied correctly.

I've added the space back and the fix should be deployed Soon™. Thanks again and sorry for the issue.

**Comment by spaze** [comment]
Hi @revisiontroll again. We've now deployed the fix for the issue and I've verified the *space* is back and that the toggle now behaves correctly. You can close the issue now if it works for you too. Thanks for letting us know and again sorry for the trouble :-)

**Comment by revisiontroll** [comment]
Confirmed, it is fixed. Thanks for the quick response!
