### ISSUE TITLE
No mention of Reporting API v1 nor Reporting-Endpoints header in setup guides

### ISSUE THREAD

**Issue by scarytom** [report-uri/report-uri-bugs#164]
I'm currently trying to decide between https://report-uri.com/ and https://www.uriports.com/ (which appears to be your main competitor).

As part of my evaluation, I've been going through the setup guides on both sites.  I note that uriports were very quick of the mark when the reporting API v1 was released, publishing a useful [blog post](https://www.uriports.com/blog/reporting-api-v1/) and updating their [getting started](https://www.uriports.com/getting-started-with-website-monitoring#reporting-api) pages.  I am a little dismayed to see no mention of this anywhere on report-uri.

**Comment by ScottHelme** [comment]
Hi @scarytom,

We've supported the Reporting API since it was launched, having support on our service for beta testing before it reached stable in Chrome. Our [documentation](https://docs.report-uri.com/setup/reporting-api/) covers our support for the Reporting API and I also blogged about it on my [personal blog](https://scotthelme.co.uk/introducing-the-reporting-api-nel-other-major-changes-to-report-uri/) at the time. The [Setup](https://report-uri.com/account/setup/) page in your account contains a section titled 'Reporting API' and contains the necessary configuration to enable it, with a link through to our documentation (the small 'i' icon). Hope that helps!
