### ISSUE TITLE
Filter CSP reports generated by browser malware

### ISSUE THREAD

**Issue by gwire** [report-uri/report-uri-bugs#42]
I see numerous requests for loading javascript from "loadingpaqes.info", which based on search results (including [this CSP focused page](https://github.com/nico3333fr/CSP-useful/blob/master/csp-wtf/explained.md)) comes from macOS malware.

```
{
    "csp-report": {
        "document-uri": "https://www.example.com/",
        "referrer": "https://www.google.co.in/",
        "violated-directive": "script-src",
        "effective-directive": "script-src",
        "original-policy": "default-src https: 'self' data:; font-src https: data:; img-src https: data:; script-src https: 'self' data: 'unsafe-inline' 'unsafe-eval'; style-src https: 'unsafe-inline'; report-uri https://example.report-uri.io/r/default/csp/enforce",
        "disposition": "enforce",
        "blocked-uri": "http://loadingpaqes.info/jo/is?id=6639AE8A-AF07-5B89-8D35-0ED339B08191&d=2712c147-7e15-4366-80e0-4c7b98d780f0&cl=upd",
        "line-number": 1,
        "column-number": 264,
        "status-code": 0,
        "script-sample": ""
    }
}
```

**Comment by ScottHelme** [comment]
Filtering on the blocked-uri alone is petty hard, especially when a new variant of malware uses a new domain. If there's some way to reliably and accurate categorise these we will filter them. After the v2 launch my goal is to now refine this system and get some automated detection for these things in place.

**Comment by lstrojny** [comment]
A way to manually filter URLs would probably be a good solution in the meantime.

**Comment by owangen** [comment]
We need better filter solution now, we get flooded with reports generated by malware and after I have analysed them I would like to be able to filter them away.
And yes, a more automatic way to categorize and analyse CSP reports would be a killer feature, but a static filter would do in the meantime.

**Comment by ScottHelme** [comment]
If you have a report that is generated by malware and we can be confident that's the case, we're happy to filter these at a global level. Please file a ticket with a smaple JSON payload and evidence, with that we can confirm and get it filtered pretty quickly!

**Comment by owangen** [comment]
But how would you implement that? Do you think about implementing it like a global filter with known adware and give the user the possiblity to turn the global filter on or off? If so, then the user also need to be able to inspect what the filter contains.

Another example is google (or bing) translate image https://www.gstatic.com/images/branding/product/2x/translate_24dp.png. We won't add it to our CSP, but we also don't need to see the reports each time this happens.

**Comment by ScottHelme** [comment]
The global filters we offer can be seen on the Filters page in your account and you can configure whether or not you would like them applied to your account. We don't publicise all of our filtering criteria mostly because they're fairly complicated and large now (how do we show lists of 100s of domains?).

Something like the Google Translate example you gave would be more likely to be covered by customised filters which we'd like to introduce.

**Comment by owangen** [comment]
I see. Even though I don't want to see all the reports generated by known adware, it could be nice to see statistics on how much adware "threats" CSP has saved our users using our website.
Anyway, I will file a ticket with sample JSON payload of top reports caused by what we think is adware, and the reason why we think it's adware

**Comment by ScottHelme** [comment]
This has now been added to our filters.
