### ISSUE TITLE
No possibility to filter URI

### ISSUE THREAD

**Issue by KommX** [report-uri/report-uri-bugs#43]
In v2 there is no filter anymore for the field "URI", which was there in v1.
Is there a reason for that?

**Comment by ScottHelme** [comment]
Hi @KommX, do you mean this one?

![screenshot 2017-11-03 14 06 39](https://user-images.githubusercontent.com/5352840/32377648-485f40b4-c0a0-11e7-9fae-9bee7700a555.png)

It's now a text field so you can search on any domain/subdomain you collect for.

**Comment by KommX** [comment]
Ok, I see.
But if you're monitoring > 10 sites, you all have to type them?
So, that's no bug but I disagree with the design decision. :)

**Comment by ScottHelme** [comment]
The problem was that if people were monitoring 10 sites with 3-4 subdomains on each then you had a list of 30-40 items. It gets a lot worse as you monitor more domains or subdomains too, the list quickly became problematic. 

If you have any ideas on how to improve it I'd love to hear them, we want things to be easy to use :)

**Comment by KommX** [comment]
Perhaps some kind of combination:

- a text field that autocompletes to domains on the old list
?

**Comment by ScottHelme** [comment]
I think I can do something with that, leave it with me.

**Comment by ScottHelme** [comment]
I've updated the text input field to now do predictive suggestions based on the hosts you filter for. This is essentially the same as the dropdown field prior except it has the capability to do both! 

Thanks for the feedback.
