### ISSUE TITLE
Indicate which sites are currently filtered

### ISSUE THREAD

**Issue by oliversalzburg** [report-uri/report-uri-bugs#91]
In the free offering, we are currently limited to 3 sites. This is fine, but it would be nice to know what I am missing. I can see that hundreds of reports are filtered, it'd be helpful to see what was filtered.

That might also be an incentive to chose a paid plan ;)

**Comment by ScottHelme** [comment]
Hey @oliversalzburg, thanks for the bug. 

The filtered reports do not count towards your quota largely because we do not process them or even store any meta data about them. They could have been filtered because of any of the settings you've configured on the Filters page or because they were sent for a site that you don't have listed to collect reports for.

For us to keep info on the reports that are filtered they'd need to count towards your quota and that wasn't something we wanted to do!

**Comment by oliversalzburg** [comment]
Hi @ScottHelme,

thanks for the explanation, but I figured it would work like that. I thought, maybe a different model could provide more benefits and a greater incentive to go for a paid plan.

But, I guess, it's too big of a change to your current approach. So I understand if this is unlikely to change.
